MindU_I2/MindU_I2/Controllers/ArtsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using MindU_I2.Models;

namespace MindU_I2.Controllers
{
    public class ArtsController : Controller
    {
        private MindUEntities db = new MindUEntities();

        // GET: Arts
        public ActionResult Index()
        {
            return View(db.Arts.ToList());
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

MindU_I2/MindU_I2/Controllers/HomeController.cs
using MindU_I2.Models;
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;

namespace MindU_I2.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {

            return View();
        }
        public ActionResult HelpLine()
        {
            return View();
        }

    }

}

MindU_I2/MindU_I2/Controllers/SportsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using MindU_I2.Models;

namespace MindU_I2.Controllers
{
    public class SportsController : Controller
    {
        private MindUEntities db = new MindUEntities();

        // GET: Sports
        public ActionResult Index()
        {
            return View(db.Sports.ToList());
        }

        // GET: Sports/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Sport sport = db.Sports.Find(id);
            if (sport == null)
            {
                return HttpNotFound();
            }
            return View(sport);
        }

        // GET: Sports/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Sports/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "sid,name,address,suburb,postcode,state,category,contact")] Sport sport)
        {
            if (ModelState.IsValid)
            {
                db.Sports.Add(sport);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(sport);
        }

        // GET: Sports/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Sport sport = db.Sports.Find(id);
            if (sport == null)
            {
                return HttpNotFound();
            }
            return View(sport);
        }

        // POST: Sports/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "sid,name,address,suburb,postcode,state,category,contact")] Sport sport)
        {
            if (ModelState.IsValid)
            {
                db.Entry(sport).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(sport);
        }

        // GET: Sports/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Sport sport = db.Sports.Find(id);
            if (sport == null)
            {
                return HttpNotFound();
            }
            return View(sport);
        }

        // POST: Sports/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Sport sport = db.Sports.Find(id);
            db.Sports.Remove(sport);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

MindU_I2/MindU_I2/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}

<!-- Page Content -->
<div class="container">
    <section class="about" id="about">
        <!-- Page Heading/Breadcrumbs -->
        <div>
            <ol class="breadcrumb" style="background-color:transparent;">
                <li class="breadcrumb-item">
                    <a href="@Url.Action("index", "Home")">
                        <img class="active" src="@Url.Content("~/Images/home_icon2.png")">
                    </a>
                </li>
                <li class="breadcrumb-item active">About MindVictoria</li>
            </ol>
        </div>
        <!-- Intro Content -->
        <div class="row">
            <div class="col-lg-7 col-md-12 col-sm-12">
                <h2 class="about_h">MindVictoria Project</h2>
                <p class="about_font">MindVictoria is a project aiming at helping people who are concerned with international students who are struggling with stress, anxiety and loneliness in VIC.</p>
                <p class="about_font">
                    We provide art spaces, sports and mental health relevant information such as mental health services and tips for you to help your international student friend  get engaged in a more bright world!!!
                    Whether you are new to melbourne or a person who does not know how to help your international friend get out of negative mood, welcome to visit MindVictoria to have fun and give feedback for our project.
                </p>
            </div>
            <div class="col-lg-5 col-md-12 col-sm-12">
                <img src="@Url.Content("~/Images/banners/about_banner1.jpg")" alt="About us">
            </div>
        </div>
    </section>
    </div>
    <!-- /.row -->

MindU_I2/MindU_I2/Views/Home/HelpLine.cshtml
@{
    ViewBag.Title = "HelpLine";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>

<div class="container">
    <div class="col-lg-12 col-md-12">
        <img style="width:100%;" src="@Url.Content("~/Images/banners/help_banner.jpg")">
    </div>
    <div>
        <ol class="breadcrumb" style="background-color:transparent;">
            <li class="breadcrumb-item">
                <a href="@Url.Action("index", "Home")">
                    <img class="active" src="@Url.Content("~/Images/home_icon2.png")">
                </a>
            </li>
            <li class="breadcrumb-item active">Helplines</li>
        </ol>
    </div>
    <div class="col-lg-8 col-md-8" id="slide_div1">
        <div class="card">
            <p class="card__distance">&nbsp;</p>
            <h2 class="card-title" style="color:orangered; font:bold;">
                Headspace
            </h2>
            <div class="card-body">
                <p class="card-text">
                    Headspace is a confidential, free and secure space where young people 12 - 25 or their family can chat, email or speak on the phone with a qualified youth mental health professional.
                </p>
                <p class="card-text">
                    <h4>
                        Call 1800 650 890
                    </h4>
                </p>
            </div>
            <p class="card__distance">&nbsp;</p>
        </div>
    </div>
    <div class="col-lg-8 col-md-8" id="slide_div2">
        <div class="card">
            <p class="card__distance">&nbsp;</p>
            <h2 class="card-title" style="color:orangered; font:bold;">
                Butterfly's National Helpline
            </h2>
            <div class="card-body">
                <p class="card-text">
                    The Butterfly Foundation’s National Helpline, ED HOPE, is a free and confidential service which provides information, counselling and treatment referral for eating disorders, disordered eating, body image and related issues.
                </p>
                <p class="card-text">
                    <h4>
                        Call 1800 33 4673, 8am – midnight AEST / 7 days a week.

                    </h4>
                </p>
            </div>
            <p class="card__distance">&nbsp;</p>
        </div>
    </div>
    <div class="col-lg-8 col-md-8" id="slide_div3">
        <div class="card">
            <p class="card__distance">&nbsp;</p>
            <h2 class="card-title" style="color:orangered; font:bold;">
                Suicide Call Back Service
            </h2>
            <div class="card-body">
                <p class="card-text">
                    SANE Australia provides support, training and education enabling those with a mental illness to lead a better life.
                </p>
                <p class="card-text">
                    <h4>
                        Call 1800 18 7263, 9am-5pm AEST (Mon-Fri)
                    </h4>
                </p>
            </div>
            <p class="card__distance">&nbsp;</p>
        </div>
    </div>
    <div class="col-lg-8 col-md-8" id="slide_div4">
        <div class="card">
            <p class="card__distance">&nbsp;</p>
            <h2 class="card-title" style="color:orangered; font:bold;">
                Lifeline
            </h2>
            <div class="card-body">
                <p class="card-text">
                    Lifeline provides 24-hour crisis counseling, support groups and suicide prevention services.
                </p>
                <p class="card-text">
                    <h4>
                        Call 13 11 14
                    </h4>
                </p>
            </div>
            <p class="card__distance">&nbsp;</p>
        </div>
    </div>
    <div class="col-lg-8 col-md-8" id="slide_div5">
        <div class="card">
            <p class="card__distance">&nbsp;</p>
            <h2 class="card-title" style="color:orangered; font:bold;">
                Beyondblue
            </h2>
            <div class="card-body">
                <p class="card-text">
                    beyondblue aims to increase awareness of depression and anxiety and reduce stigma.
                </p>
                <p class="card-text">
                    <h4>
                        Call 1300 22 4636, 24 hours / 7 days a week.
                    </h4>
                </p>
            </div>
            <p class="card__distance">&nbsp;</p>
        </div>
    </div>
    <div class="col-lg-8 col-md-8" id="slide_div6">
        <div class="card">
            <p class="card__distance">&nbsp;</p>
            <h2 class="card-title" style="color:orangered; font:bold;">
                SANE Australia
            </h2>
            <div class="card-body">
                <p class="card-text">
                    SANE Australia provides support, training and education enabling those with a mental illness to lead a better life.
                </p>
                <p class="card-text">
                    <h4>
                        Call 1800 18 7263, 9am-5pm AEST (Mon-Fri).
                    </h4>
                </p>
            </div>
            <p class="card__distance">&nbsp;</p>
        </div>
    </div>
</div>

<script>
    $(document).ready(function () {
        $("#slide_div1").animate({ left: '200px' });
        $("#slide_div2").animate({ left: '200px' });
        $("#slide_div3").animate({ left: '200px' });
        $("#slide_div4").animate({ left: '200px' });
        $("#slide_div5").animate({ left: '200px' });
        $("#slide_div6").animate({ left: '200px' });
    });
</script>

MindU_I2/MindU_I2/Views/Home/Index.cshtml
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
    ViewBag.Title = "Home";
}
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>

<!--Carousel-->
<div id="myCarousel" class="carousel slide" data-ride="carousel">
    <!-- Indicators -->
    <ol class="carousel-indicators">
        <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
        <li data-target="#myCarousel" data-slide-to="1"></li>
    </ol>
    <!-- Wrapper for slides -->
    <div class="carousel-inner">
        <div class="item active">
            <img src="@Url.Content("~/Images/banners/banner2.jpg")" alt="Mind U" style="width:100%">
            <div class="carousel-caption">
                <h1 style="font-size:40px;">Mind U</h1>
                <p style="font-size:40px;">You are not alone</p>
            </div>
        </div>
        <div class="item">
            <img src="@Url.Content("~/Images/banners/banner3.jpg")" alt="Mental Health">
            <div class="carousel-caption">
                <h1 style="font-size:40px">Mental Health</h1>
                <p style="font-size:30px">We are here to help</p>
            </div>
        </div>
    </div>
    <!-- Left and right controls -->
    <a class="left carousel-control" href="#myCarousel" data-slide="prev">
        <span class="glyphicon glyphicon-chevron-left"></span>
        <span class="sr-only">Previous</span>
    </a>
    <a class="right carousel-control" href="#myCarousel" data-slide="next">
        <span class="glyphicon glyphicon-chevron-right"></span>
        <span class="sr-only">Next</span>
    </a>
    <!--/.Carousel-->
</div>
<!-- Page Content -->
<div class="container">
    <!--Section Leisure-->
    <section class="leisure" id="leisure">
        <div class="row">
            <div class="col-lg-4 col-md-6 col-sm-6  leisure-item">
                <div class=" box_image" style="background-color:rgba(0, 255, 255,0.7)">
                    <a href='@Url.Action("Index", "Arts")'>
                        <img class="box_img" src="@Url.Content("~/Images/boxes/art_icon.jpg")" alt="arts">
                    </a>
                    <div class="overlay">
                        <p>Art mesume,Art gallery</p>
                    </div>
                </div>
            </div>
            <div class="col-lg-4 col-md-6 col-sm-6  leisure-item">
                <div class="box_image">
                    <a href='@Url.Action("Index", "Sports")'>
                        <img class="box_img" src="@Url.Content("~/Images/boxes/sports_icon.jpg")" alt="sports">
                    </a>
                    <div class="overlay">
                        <p>Yoga,Pilates...</p>
                    </div>
                </div>
            </div>
            <div class="col-lg-4 col-md-6 col-sm-6 leisure-item">
                <div class="box_image">
                    <a href='#'>
                        <img class="box_img" src="@Url.Content("~/Images/boxes/preference_icon.jpg")" alt="preference">
                    </a>
                    <div class="overlay">
                        <p>Customise search</p>
                    </div>
                </div>
            </div>
            <!-- /.row -->
        </div>
    </section>
    <!--.Section Leisure-->
    <!--Section Services-->
    <hr style="width:3%;">
    <section class="services" id="services">
        <div class="row">
            <div class="col-lg-4 col-md-6 services-item">
                <div class="box_image">
                    <a href='@Url.Action("Index", "Arts")'>
                        <img class="box_img" src="@Url.Content("~/Images/boxes/conditions_icon.jpg")" alt="conditions">
                    </a>
                    <div class="overlay">
                        <p>Common mental health condtions</p>
                    </div>
                </div>
            </div>
            <div class="col-lg-4 col-md-6 col-sm-6 services-item">
                <div class="box_image">
                    <a href='@Url.Action("Index", "Sports")'>
                        <img class="box_img" src="@Url.Content("~/Images/boxes/professional_help.jpg")" alt="professinal help">
                    </a>
                    <div class="overlay">
                        <p>Find professinal help?</p>
                    </div>
                </div>
            </div>
            <div class="col-lg-4 col-md-6 col-sm-6 services-item">
                <div class="box_image">
                    <a href='@Url.Action("Index", "Sports")'>
                        <img class="box_img" src="@Url.Content("~/Images/boxes/tips.jpg")" alt="tips">
                    </a>
                    <div class="overlay">
                        <p>How to help?</p>
                    </div>
                </div>
            </div>
            <!-- /.row -->
        </div>
    </section>
    <!--.Section Leisure-->
</div>
@Scripts.Render("~/Scripts/overlay_script.js")